# Generated by Django 5.0.6 on 2024-06-09 06:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy')], max_length=255)),
                ('length', models.PositiveIntegerField()),
                ('image_card', models.FileField(blank=True, null=True, upload_to='image_card/')),
                ('image_cover', models.FileField(blank=True, null=True, upload_to='images_cover/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('movie_views', models.IntegerField(default=0)),
                ('uu_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tmdb_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.movie')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
