# Generated by Django 5.0.6 on 2024-06-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_card',
            field=models.FileField(blank=True, null=True, upload_to='image_card/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image_cover',
            field=models.FileField(blank=True, null=True, upload_to='images_cover/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
