# Generated by Django 5.0.6 on 2024-06-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_movielist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielist',
            old_name='owener_user',
            new_name='owner_user',
        ),
    ]
